### ISSUE TITLE
Credentials Exposed

### ISSUE THREAD

**Issue by csquared** [rprez/mape-app#4]
https://github.com/rprez/mape-app/blob/55baf1d4a2faf317e9ae6defde0cab96272a3ba5/config.py#L13-L17

Hi there:
Chris from Bucketeer here. These credentials are on the public internet. I've rolled them and new ones are available in your Heroku app - please keep them private in the future!
Cheers,
Chris

**Comment by rprez** [comment]
Hi Chris,

Thank you very much for your warning and changing the credentials. In a intent to public my work I forgot to scan the commits. 

Thanks a lot, 
Greetings,
